In [29]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [36]:
weight = torch.tensor([0.0051, 0.0077, 0.0121, 0.0195, 0.0319, 0.0525, 0.0868, 0.1443, 0.2409,
                             0.3993])
input = torch.tensor([[2.9751, -0.3312, -7.4666, -6.8384, 1.6987, 1.9255, -2.2512, -1.4505,
                           0.7402, 2.1339],
                          [3.3333, -0.6700, -7.6600, -5.8551, 1.3606, 2.1366, -1.8532, -1.4562,
                           0.4192, 3.1757],
                          [3.5510, -0.6564, -8.6301, -5.3536, 1.2964, 1.1514, -2.4029, -0.6956,
                           0.1640, 3.3132],
                          [3.1342, 0.3029, -8.1702, -6.4352, 1.0989, 2.1021, -2.5321, -1.5944,
                           0.4383, 2.3836]])
target = torch.tensor([0, 6, 2, 0])
gamma = 1
myloss = torch.tensor(0.8269)

In [75]:
softmax = F.softmax(input, dim=1)
label_one_hot = F.one_hot(target, input.shape[-1]).float()
pt = softmax
log_softmax = F.log_softmax(input, dim=1)
FL= -(1-pt) ** gamma * log_softmax *label_one_hot
print(pt)
print(FL)
print((FL*weight).sum(dim=1).mean())

tensor([[4.5017e-01, 1.6499e-02, 1.3140e-05, 2.4628e-05, 1.2562e-01, 1.5759e-01,
         2.4189e-03, 5.3872e-03, 4.8169e-02, 1.9411e-01],
        [4.1982e-01, 7.6639e-03, 7.0588e-06, 4.2913e-05, 5.8388e-02, 1.2686e-01,
         2.3474e-03, 3.4914e-03, 2.2776e-02, 3.5860e-01],
        [4.8786e-01, 7.2618e-03, 2.5010e-06, 6.6233e-05, 5.1184e-02, 4.4275e-02,
         1.2663e-03, 6.9826e-03, 1.6494e-02, 3.8461e-01],
        [4.7669e-01, 2.8095e-02, 5.8722e-06, 3.3289e-05, 6.2276e-02, 1.6983e-01,
         1.6497e-03, 4.2134e-03, 3.2168e-02, 2.2504e-01]])
tensor([[ 0.4388,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  6.0402,  0.0000,
          0.0000,  0.0000],
        [ 0.0000,  0.0000, 12.8988,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.3877,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000]])
tensor

In [31]:
cent_loss = F.cross_entropy(input, target, reduction='none')
cent_loss

tensor([ 0.7981,  6.0544, 12.8988,  0.7409])

In [25]:
pt = torch.exp(-cent_loss)
pt

tensor([0.9959, 0.5912, 0.8555, 0.9962])

In [21]:
softmax = F.softmax(input, dim=1)
softmax

tensor([[4.5017e-01, 1.6499e-02, 1.3140e-05, 2.4628e-05, 1.2562e-01, 1.5759e-01,
         2.4189e-03, 5.3872e-03, 4.8169e-02, 1.9411e-01],
        [4.1982e-01, 7.6639e-03, 7.0588e-06, 4.2913e-05, 5.8388e-02, 1.2686e-01,
         2.3474e-03, 3.4914e-03, 2.2776e-02, 3.5860e-01],
        [4.8786e-01, 7.2618e-03, 2.5010e-06, 6.6233e-05, 5.1184e-02, 4.4275e-02,
         1.2663e-03, 6.9826e-03, 1.6494e-02, 3.8461e-01],
        [4.7669e-01, 2.8095e-02, 5.8722e-06, 3.3289e-05, 6.2276e-02, 1.6983e-01,
         1.6497e-03, 4.2134e-03, 3.2168e-02, 2.2504e-01]])

In [23]:
F.nll_loss(softmax, target)

tensor(-0.2323)